import os
import sys
import json
import importlib
from typing import Dict, Any
from langchain_core.messages import AIMessage
from dotenv import load_dotenv
import litellm

# Establish path references for cross-module state access
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(os.path.dirname(__file__))
AgentState = importlib.import_module("3_state_definition").AgentState
from translation_utils import translate_to_arabic, litellm_completion_with_groq_key_fallback
from prompts import NARRATIVE_GENERATION_PROMPT, DISCUSSION_PROMPT, ANALYZE_PROMPT

# Load API Keys securely from the parent environment
load_dotenv(os.path.join(os.path.dirname(__file__), "../../.env"))
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    print("!!! [WARNING] GEMINI_API_KEY not found.")
else:
    os.environ["GEMINI_API_KEY"] = gemini_api_key

groq_api_key = os.getenv("GROQ_API_KEY")
if groq_api_key:
    os.environ["GROQ_API_KEY"] = groq_api_key

AGENT_CONFIG = importlib.import_module("1_agent_config").AGENT_CONFIG
PRIMARY_MODEL = AGENT_CONFIG["model"]
FALLBACK_MODELS_LIST = AGENT_CONFIG.get("fallback_models", [])

def translator_node(current_state: AgentState) -> Dict[str, Any]:
    """
    NODE 3: Narrative Generation (The Tongue)
    This node converts raw, backend data frames and execution states into 
    highly polished, conversational English suitable for a premium clientele.
    """
    detected_intent = current_state.get("active_intent")
    missing_required_fields = current_state.get("missing_info", [])
    tool_execution_results = current_state.get("tool_outputs", {})
    user_language = current_state.get("user_language", "en")
    dialogue_act = current_state.get("dialogue_act", "general")

    print(f"--- [TONGUE] Generating Professional Response ---")

    # 0. Handle API quota exhaustion gracefully by alerting the user explicitly
    if "__quota_exceeded__" in missing_required_fields:
        rate_limit_message = (
            "[!] The AI model is temporarily rate-limited by the API provider. "
            "Please wait a few minutes and try again. Your request has been noted."
        )
        if user_language.startswith("ar"):
            rate_limit_message = translate_to_arabic(rate_limit_message)
        return {"messages": [AIMessage(content=rate_limit_message)]}
    
    # 1. Handle Missing Information dynamically: Differentiate organic misses vs Auditor overrides
    actual_missing_fields = [missing_item for missing_item in missing_required_fields if not str(missing_item).startswith("CORRECTION:")]
    auditor_correction_hint = next((str(missing_item).replace("CORRECTION: ", "") for missing_item in missing_required_fields if str(missing_item).startswith("CORRECTION:")), None)

    if actual_missing_fields:
        # Provide human-friendly definitions for system keys
        human_readable_field_mapping = {
            "town": "location",
            "location": "preferred area or neighborhood (e.g. Fifth Settlement, Maadi)",
            "district": "neighborhood or district",
            "subdistrict": "compound or sub-area",
            "property_type": "type of property (apartment/villa)",
            "category": "whether you are looking to buy or rent",
            "user_name": "full name",
            "phone": "phone number",
            "date": "preferred date for the viewing",
            "property_id": "listing ID of the property you'd like to visit",
            "property_reference": "listing ID of the property you are referring to"
        }
        translated_missing_fields = [human_readable_field_mapping.get(field, field) for field in actual_missing_fields]
        
        if detected_intent == "book":
            missing_info_response = f"It would be my absolute pleasure to schedule a property viewing for you with one of our expert consultants! To finalize the appointment, could you please share your {', '.join(translated_missing_fields)}?"
        elif detected_intent == "search":
            missing_info_response = f"I'd love to help you find the perfect home! To narrow down the options, could you please specify the {', '.join(translated_missing_fields)}?"
        else:
            missing_info_response = f"To assist you better with this, could you please clarify the {', '.join(translated_missing_fields)}?"
        if user_language.startswith("ar"):
            missing_info_response = translate_to_arabic(missing_info_response)
        return {
            "messages": [AIMessage(content=missing_info_response)],
            "response_plan": {
                "answer_first": missing_info_response,
                "evidence_block": [],
                "next_step_prompt": "Ask for the minimum missing fields only."
            }
        }

    # 2. Process Intent Paths
    if detected_intent == "search":
        # Extract underlying context metrics generated by the Recommender/Analyzer
        market_pulse_context = tool_execution_results.get("market_context") or ""
        property_valuation_briefs = tool_execution_results.get("valuation_briefs") or []
        recommendation_results = tool_execution_results.get("recommendations") or {}
        candidate_properties = recommendation_results.get("candidates") or []
        user_maximum_budget = current_state.get("current_filters", {}).get("price_max")
        user_minimum_budget = current_state.get("current_filters", {}).get("price_min")
        if user_minimum_budget and user_maximum_budget:
            try:
                budget_bracket_instruction = (
                    f"The user's budget band is roughly {float(user_minimum_budget)/1e6:.1f}–{float(user_maximum_budget)/1e6:.1f} million EGP; "
                    "describe it that way (do not shift to a higher bracket)."
                )
            except (TypeError, ValueError):
                budget_bracket_instruction = "Mention the user's stated budget naturally."
        else:
            budget_bracket_instruction = None
        
        # Expert Logic: Pre-process property data with humanized tags before sending to LLM context
        storytelling_processed_properties = []
        for property_data in candidate_properties[:3]:
            enhanced_property_dict = property_data.copy()
            enhanced_property_dict['status'] = "Ready to move in" if str(property_data.get('completion_status')).lower() == 'completed' else "Under construction"
            enhanced_property_dict['size_desc'] = f"Generous {property_data.get('area_value')} sqm layout"
            
            if user_minimum_budget and user_maximum_budget and property_data.get('price_egp'):
                try:
                    property_price = float(property_data['price_egp'])
                    mid = (float(user_minimum_budget) + float(user_maximum_budget)) / 2.0
                    enhanced_property_dict['budget_fit'] = f"Within stated band vs midpoint {(property_price/mid)*100:.1f}%"
                except ValueError:
                    pass
            elif user_maximum_budget and property_data.get('price_egp'):
                try:
                    property_price = float(property_data['price_egp'])
                    target_budget = float(user_maximum_budget)
                    enhanced_property_dict['budget_fit'] = f"Aligns with {(property_price/target_budget)*100:.1f}% of your target"
                except ValueError:
                    pass
            storytelling_processed_properties.append(enhanced_property_dict)
        
        # When the query is vague, quietly ask one refinement question at the end — never frame it as insufficient data.
        is_vague_query = recommendation_results.get("is_vague", False)

        auditor_instruction = auditor_correction_hint if auditor_correction_hint else "None. Just be the best consultant."

        narrative_generation_prompt = NARRATIVE_GENERATION_PROMPT.format(
            budget_bracket_instruction=budget_bracket_instruction or "Use the user's maximum budget hint when describing price fit.",
            market_pulse_context=market_pulse_context if market_pulse_context else 'None',
            property_valuation_briefs=json.dumps(property_valuation_briefs, indent=2),
            storytelling_processed_properties=json.dumps(storytelling_processed_properties, indent=2),
            end_with_instruction='- END WITH: Close by asking one refinement question (e.g. preferred floor, payment plan, or delivery timeline).' if is_vague_query else '',
            auditor_instruction=auditor_instruction
        )
        
        try:
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Calling Model: {target_llm_model} ---")
            llm_response = litellm_completion_with_groq_key_fallback(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": narrative_generation_prompt},
                    {"role": "user", "content": "Explain these options to me naturally."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model

            if "/" not in actual_model_used:
                for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                    if actual_model_used in fallback_candidate:
                        actual_model_used = fallback_candidate
                        break

            final_narrative_text = llm_response.choices[0].message.content
            if user_language.startswith("ar"):
                final_narrative_text = translate_to_arabic(final_narrative_text)
            print(f"--- [TONGUE] Target: {target_llm_model} | Actual: {actual_model_used} ---")
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] LLM Call failed: {llm_error}")
            final_narrative_text = "I've analyzed the market and found some options for you. However, I'm having trouble generating the detailed report right now. Would you like to see the raw list?"
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=final_narrative_text)],
            "active_model": actual_model_used,
            "response_plan": {
                "answer_first": final_narrative_text.split("\n")[0] if final_narrative_text else "",
                "evidence_block": storytelling_processed_properties[:3],
                "next_step_prompt": "Offer one precise follow-up preference question."
            }
        }

    elif detected_intent == "analyze":
        synthesis_report = tool_execution_results.get("analyzer_synthesis", "")
        if not synthesis_report:
            synthesis_report = "I'm sorry, I couldn't generate the market analysis at this time. Please try again."
            
        analyze_prompt = ANALYZE_PROMPT.format(synthesis_report=synthesis_report)
        
        try:
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Analyze Mode - Calling Model: {target_llm_model} ---")
            llm_response = litellm_completion_with_groq_key_fallback(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": analyze_prompt},
                    {"role": "user", "content": "Deliver the analysis to the client."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model
            final_narrative_text = llm_response.choices[0].message.content
            if user_language.startswith("ar"):
                final_narrative_text = translate_to_arabic(final_narrative_text)
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] Analyze LLM failed: {llm_error}")
            final_narrative_text = synthesis_report
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=final_narrative_text)],
            "active_model": actual_model_used,
            "response_plan": {
                "answer_first": final_narrative_text.split("\n")[0] if final_narrative_text else "",
                "evidence_block": [{"type": "analysis_report"}],
                "next_step_prompt": "Offer to search for properties based on this analysis."
            }
        }

    elif detected_intent == "book" and "booking_response" in tool_execution_results:
        booking_registration_result = tool_execution_results["booking_response"]

        if booking_registration_result["status"] == "SUCCESS":
            booking_success_message = f"Fantastic! I've successfully registered your appointment. Your Booking ID is **{booking_registration_result['booking_id']}**. One of our expert consultants will contact you shortly to confirm the details."
        else:
            booking_success_message = "I'm sorry, I couldn't complete the registration. It seems some information is still missing. Could you please provide your name and phone number?"
        if user_language.startswith("ar"):
            booking_success_message = translate_to_arabic(booking_success_message)
        return {
            "messages": [AIMessage(content=booking_success_message)],
            "response_plan": {
                "answer_first": booking_success_message,
                "evidence_block": [booking_registration_result],
                "next_step_prompt": "Offer to adjust booking date/time if needed."
            }
        }

    elif detected_intent == "discussion":
        # [DISCUSSION] Provide consultant-like analysis and opinions on properties being discussed
        discussion_briefs = tool_execution_results.get("discussion_briefs", [])
        discussion_context = tool_execution_results.get("discussion_context", {})
        recent_properties = current_state.get("recent_properties", [])
        current_filters = current_state.get("current_filters", {})

        # ── KEY FIX: Extract the actual user question to anchor the LLM response ──
        all_messages = current_state.get("messages", [])
        actual_user_question = ""
        for msg in reversed(all_messages):
            if getattr(msg, "type", "") == "human":
                actual_user_question = getattr(msg, "content", "") or ""
                break

        question_type = discussion_context.get("question_type", "general")
        focused_property = tool_execution_results.get("focused_property", {}) or {}
        comparison_set = tool_execution_results.get("comparison_set", []) or []

        # ── Per-question-type response strategy so the LLM knows exactly what to produce ──
        question_type_instructions = {
            "comparison": (
                "The user wants a DIRECT COMPARISON. Do this:\n"
                "1. In sentence 1, state the single most important difference (price, size, or location).\n"
                "2. Give a clear verdict: which property better fits their goals and WHY in 1-2 sentences.\n"
                "3. Do NOT pad with generic real estate advice unrelated to these specific properties."
            ),
            "details": (
                "The user wants SPECIFIC DETAILS about one property. Do this:\n"
                "1. Lead with the most relevant fact they are asking about.\n"
                "2. Cover: price per sqm (if area available), payment method, completion status, location advantage.\n"
                "3. Give a short investment angle. Be factual and concrete — no generic preamble."
            ),
            "opinion": (
                "The user wants YOUR EXPERT OPINION. Do this:\n"
                "1. State your opinion clearly in sentence 1 (e.g., 'Yes, this is a strong buy because...').\n"
                "2. Back it with exactly 2-3 specific data points from the property facts provided.\n"
                "3. Mention one risk or caveat. Do NOT hedge with vague or generic statements."
            ),
            "general": (
                "The user asked a follow-up question. Do this:\n"
                "1. Answer their specific question directly — do NOT restate property listings unprompted.\n"
                "2. Anchor every claim to actual property facts (ID, price, location, bedrooms).\n"
                "3. If the question is ambiguous, ask ONE precise clarifying question."
            ),
        }
        specific_strategy = question_type_instructions.get(question_type, question_type_instructions["general"])

        # ── Format prices properly for deterministic anchor sentence ──
        def _fmt_price(val):
            try:
                return f"{float(val):,.0f}"
            except (TypeError, ValueError):
                return str(val) if val else "N/A"

        reference_intro = "About the property you referenced"
        if focused_property.get("listing_id"):
            reference_intro = f"About listing #{focused_property.get('listing_id')}"

        deterministic_answer = ""
        if dialogue_act == "compare" and len(comparison_set) >= 2:
            left = comparison_set[0]
            right = comparison_set[1]
            deterministic_answer = (
                f"Comparing listing #{left.get('listing_id')} vs #{right.get('listing_id')}: "
                f"The first is {_fmt_price(left.get('price_egp'))} EGP in {left.get('town')} "
                f"({left.get('bedrooms')}BR, {left.get('property_type')}), "
                f"the second is {_fmt_price(right.get('price_egp'))} EGP in {right.get('town')} "
                f"({right.get('bedrooms')}BR, {right.get('property_type')})."
            )
        elif focused_property:
            deterministic_answer = (
                f"{reference_intro}: {_fmt_price(focused_property.get('price_egp'))} EGP, "
                f"{focused_property.get('bedrooms')} bedrooms, {focused_property.get('property_type')}, "
                f"in {focused_property.get('district') or focused_property.get('town')}."
            )

        auditor_instruction = auditor_correction_hint if auditor_correction_hint else "None."

        discussion_prompt = DISCUSSION_PROMPT.format(
            actual_user_question=actual_user_question,
            question_type=question_type,
            specific_strategy=specific_strategy,
            focused_property=json.dumps(focused_property, indent=2),
            comparison_set=json.dumps(comparison_set[:3], indent=2),
            discussion_briefs=json.dumps(discussion_briefs, indent=2),
            price_max=current_filters.get('price_max', 'Not specified'),
            town=current_filters.get('town', 'Not specified'),
            category=current_filters.get('category', 'buy').upper(),
            auditor_instruction=auditor_instruction
        )
        
        try:
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Discussion Mode - Calling Model: {target_llm_model} ---")
            llm_response = litellm_completion_with_groq_key_fallback(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": discussion_prompt},
                    {"role": "user", "content": actual_user_question or "Please give me your expert take on these properties."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model

            if "/" not in actual_model_used:
                for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                    if actual_model_used in fallback_candidate:
                        actual_model_used = fallback_candidate
                        break

            discussion_response = llm_response.choices[0].message.content
            if deterministic_answer:
                discussion_response = f"{deterministic_answer}\n\n{discussion_response}"
            if user_language.startswith("ar"):
                discussion_response = translate_to_arabic(discussion_response)
            print(f"--- [TONGUE] Discussion: {target_llm_model} | Actual: {actual_model_used} ---")
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] Discussion LLM failed: {llm_error}")
            discussion_response = deterministic_answer or "Could you clarify which property you'd like to discuss? I'm ready to go deep on the details."
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=discussion_response)],
            "active_model": actual_model_used,
            "response_plan": {
                "answer_first": deterministic_answer or (discussion_response.split("\n")[0] if discussion_response else ""),
                "evidence_block": discussion_briefs[:3],
                "next_step_prompt": "Ask one targeted next-step question tied to commute, budget, or amenities."
            }
        }

    # 3. Fallback to Idle / Greeting via LLM
    all_messages = current_state.get("messages", [])
    actual_user_question = ""
    for msg in reversed(all_messages):
        if getattr(msg, "type", "") == "human":
            actual_user_question = getattr(msg, "content", "") or ""
            break

    idle_prompt = (
        "You are an elite AI Real Estate Consultant. The user just said something casual or unrelated to a specific property search.\n"
        "Respond warmly and professionally. Briefly remind them that you can help them find properties, compare listings, provide market insights, or book viewings.\n"
        "Keep it concise (2-3 sentences max) and end with a welcoming question."
    )

    try:
        target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
        available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

        print(f"--- [TONGUE] Idle Mode - Calling Model: {target_llm_model} ---")
        llm_response = litellm_completion_with_groq_key_fallback(
            model=target_llm_model,
            messages=[
                {"role": "system", "content": idle_prompt},
                {"role": "user", "content": actual_user_question or "Hello!"}
            ],
            fallbacks=available_fallbacks
        )
        actual_model_used = llm_response.model

        if "/" not in actual_model_used:
            for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                if actual_model_used in fallback_candidate:
                    actual_model_used = fallback_candidate
                    break
                    
        idle_message = llm_response.choices[0].message.content
        if user_language.startswith("ar"):
            idle_message = translate_to_arabic(idle_message)
    except Exception as llm_error:
        print(f"!!! [TONGUE_ERROR] Idle LLM failed: {llm_error}")
        idle_message = (
            "Welcome! I am your elite AI Real Estate Consultant.\n\n"
            "Here is how I can assist you today:\n"
            "- **Find Properties:** Share your budget, preferred area, and property type.\n"
            "- **Compare & Discuss:** Ask me to compare specific listings or give my expert opinion on a property.\n"
            "- **Market Insights:** Ask about trends or valuations in areas like New Cairo.\n"
            "- **Book Viewings:** I can seamlessly schedule site visits for properties you are interested in.\n\n"
            "How may I help you navigate the market today?"
        )
        actual_model_used = getattr(current_state, "active_model", PRIMARY_MODEL)

    if user_language.startswith("ar") and "Welcome!" in idle_message:
        idle_message = translate_to_arabic(idle_message)
        
    return {
        "messages": [AIMessage(content=idle_message)],
        "active_model": actual_model_used if 'actual_model_used' in locals() else current_state.get("active_model", PRIMARY_MODEL),
        "response_plan": {
            "answer_first": idle_message,
            "evidence_block": [],
            "next_step_prompt": "Invite user to share budget, area, and property type."
        }
    }
