import os
import sys
import json
import importlib
from typing import Dict, Any
from langchain_core.messages import AIMessage
from dotenv import load_dotenv
import litellm

# Establish path references for cross-module state access
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(os.path.dirname(__file__))
AgentState = importlib.import_module("3_state_definition").AgentState
from translation_utils import translate_to_arabic, litellm_completion_with_groq_key_fallback

# Load API Keys securely from the parent environment
load_dotenv(os.path.join(os.path.dirname(__file__), "../../.env"))
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    print("!!! [WARNING] GEMINI_API_KEY not found.")
else:
    os.environ["GEMINI_API_KEY"] = gemini_api_key

groq_api_key = os.getenv("GROQ_API_KEY")
if groq_api_key:
    os.environ["GROQ_API_KEY"] = groq_api_key

AGENT_CONFIG = importlib.import_module("1_agent_config").AGENT_CONFIG
PRIMARY_MODEL = AGENT_CONFIG["model"]
FALLBACK_MODELS_LIST = AGENT_CONFIG.get("fallback_models", [])

def translator_node(current_state: AgentState) -> Dict[str, Any]:
    """
    NODE 3: Narrative Generation (The Tongue)
    This node converts raw, backend data frames and execution states into 
    highly polished, conversational English suitable for a premium clientele.
    """
    detected_intent = current_state.get("active_intent")
    missing_required_fields = current_state.get("missing_info", [])
    tool_execution_results = current_state.get("tool_outputs", {})
    user_language = current_state.get("user_language", "en")
    dialogue_act = current_state.get("dialogue_act", "general")

    print(f"--- [TONGUE] Generating Professional Response ---")

    # 0. Handle API quota exhaustion gracefully by alerting the user explicitly
    if "__quota_exceeded__" in missing_required_fields:
        rate_limit_message = (
            "[!] The AI model is temporarily rate-limited by the API provider. "
            "Please wait a few minutes and try again. Your request has been noted."
        )
        if user_language.startswith("ar"):
            rate_limit_message = translate_to_arabic(rate_limit_message)
        return {"messages": [AIMessage(content=rate_limit_message)]}
    
    # 1. Handle Missing Information dynamically: Differentiate organic misses vs Auditor overrides
    actual_missing_fields = [missing_item for missing_item in missing_required_fields if not str(missing_item).startswith("CORRECTION:")]
    auditor_correction_hint = next((str(missing_item).replace("CORRECTION: ", "") for missing_item in missing_required_fields if str(missing_item).startswith("CORRECTION:")), None)

    if actual_missing_fields:
        # Provide human-friendly definitions for system keys
        human_readable_field_mapping = {
            "town": "location", 
            "property_type": "type of property (apartment/villa)",
            "category": "whether you are looking to buy or rent"
        }
        translated_missing_fields = [human_readable_field_mapping.get(field, field) for field in actual_missing_fields]
        missing_info_response = f"I'd love to help you find the perfect home! Could you please specify the {', '.join(translated_missing_fields)}?"
        if user_language.startswith("ar"):
            missing_info_response = translate_to_arabic(missing_info_response)
        return {
            "messages": [AIMessage(content=missing_info_response)],
            "response_plan": {
                "answer_first": missing_info_response,
                "evidence_block": [],
                "next_step_prompt": "Ask for the minimum missing fields only."
            }
        }

    # 2. Process Intent Paths
    if detected_intent in ["search", "analyze"]:
        # Extract underlying context metrics generated by the Recommender/Analyzer
        market_pulse_context = tool_execution_results.get("market_context") or "No general market trends available."
        property_valuation_briefs = tool_execution_results.get("valuation_briefs") or []
        recommendation_results = tool_execution_results.get("recommendations") or {}
        candidate_properties = recommendation_results.get("candidates") or []
        user_maximum_budget = current_state.get("current_filters", {}).get("price_max")
        
        # Expert Logic: Pre-process property data with humanized tags before sending to LLM context
        storytelling_processed_properties = []
        for property_data in candidate_properties[:3]:
            enhanced_property_dict = property_data.copy()
            enhanced_property_dict['status'] = "Ready to move in" if str(property_data.get('completion_status')).lower() == 'completed' else "Under construction"
            enhanced_property_dict['size_desc'] = f"Generous {property_data.get('area_value')} sqm layout"
            
            if user_maximum_budget and property_data.get('price_egp'):
                try:
                    property_price = float(property_data['price_egp'])
                    target_budget = float(user_maximum_budget)
                    enhanced_property_dict['budget_fit'] = f"Aligns with {(property_price/target_budget)*100:.1f}% of your target"
                except ValueError:
                    pass
            storytelling_processed_properties.append(enhanced_property_dict)
        
        vague_query_instruction = (
            "The user provided very few details. Mention that more specifics would help you find an even more precise match."
            if recommendation_results.get("is_vague")
            else "The user provided good details."
        )

        auditor_instruction = auditor_correction_hint if auditor_correction_hint else "None. Just be the best consultant."

        narrative_generation_prompt = f"""
        You are an Elite Real Estate Investment Consultant (Concierge Style). 
        Your goal is to present these opportunities with sophistication and expert insight.

        MARKET TRENDS:
        {market_pulse_context}

        SPECIFIC PROPERTY VALUATIONS:
        {json.dumps(property_valuation_briefs, indent=2)}

        RECOMMENDED PROPERTIES (with budget analysis):
        {json.dumps(storytelling_processed_properties, indent=2)}

        INSTRUCTIONS FOR ELITE STORYTELLING:
        - DO NOT just list IDs and prices. Use listing IDs as references (e.g., "Our featured villa, #11225...").
        - Always mention the price, number of bedrooms, location, and property type for each property.
        - LIFESTYLE & FEATURES: Describe the "Generous layout" (Area) and the "Ideal bedroom count."
        - EXPERT ADVICE: If a property is "Ready to move in," highlight the convenience for immediate occupancy. If the payment is "Cash," mention it as a clean, straightforward transaction.
        - TONE: Warm, authoritative, and extremely helpful. Use phrases like "I've personally identified," "Standout match," or "Unique opportunity."
        - BUDGET: Mention the budget scale naturally (e.g. "In that 15 million bracket you mentioned...").
        - CATEGORIZE: 
            - "Primary Match" (The best overall alignment).
            - "Premium Selection" (A high-end option worth stretching for).
            - "Value Choice" (Excellent quality at a more conservative price).
        - CLARITY: If the Analyzer found limited data, frame it as "A niche, exclusive market opportunity."
        - If the Analyzer says a property is 'Competitive' or 'Fair Value', highlight it.
        - UNDER-SPECIFIED REQUEST: {vague_query_instruction}

        CRITICAL CORRECTION FROM AUDITOR:
        {auditor_instruction}
        """
        
        try:
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Calling Model: {target_llm_model} ---")
            llm_response = litellm_completion_with_groq_key_fallback(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": narrative_generation_prompt},
                    {"role": "user", "content": "Explain these options to me naturally."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model

            if "/" not in actual_model_used:
                for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                    if actual_model_used in fallback_candidate:
                        actual_model_used = fallback_candidate
                        break

            final_narrative_text = llm_response.choices[0].message.content
            if user_language.startswith("ar"):
                final_narrative_text = translate_to_arabic(final_narrative_text)
            print(f"--- [TONGUE] Target: {target_llm_model} | Actual: {actual_model_used} ---")
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] LLM Call failed: {llm_error}")
            final_narrative_text = "I've analyzed the market and found some options for you. However, I'm having trouble generating the detailed report right now. Would you like to see the raw list?"
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=final_narrative_text)],
            "active_model": actual_model_used,
            "response_plan": {
                "answer_first": final_narrative_text.split("\n")[0] if final_narrative_text else "",
                "evidence_block": storytelling_processed_properties[:3],
                "next_step_prompt": "Offer one precise follow-up preference question."
            }
        }

    elif detected_intent == "book" and "booking_response" in tool_execution_results:
        booking_registration_result = tool_execution_results["booking_response"]

        if booking_registration_result["status"] == "SUCCESS":
            booking_success_message = f"Fantastic! I've successfully registered your appointment. Your Booking ID is **{booking_registration_result['booking_id']}**. One of our expert consultants will contact you shortly to confirm the details."
        else:
            booking_success_message = "I'm sorry, I couldn't complete the registration. It seems some information is still missing. Could you please provide your name and phone number?"
        if user_language.startswith("ar"):
            booking_success_message = translate_to_arabic(booking_success_message)
        return {
            "messages": [AIMessage(content=booking_success_message)],
            "response_plan": {
                "answer_first": booking_success_message,
                "evidence_block": [booking_registration_result],
                "next_step_prompt": "Offer to adjust booking date/time if needed."
            }
        }

    elif detected_intent == "discussion":
        # [DISCUSSION] Provide consultant-like analysis and opinions on properties being discussed
        discussion_briefs = tool_execution_results.get("discussion_briefs", [])
        discussion_context = tool_execution_results.get("discussion_context", {})
        recent_properties = current_state.get("recent_properties", [])
        current_filters = current_state.get("current_filters", {})
        
        # Build rich context for consultative response
        comparison_context = {
            "recent_properties": recent_properties[:3],  # Latest recommendations
            "discussion_details": discussion_briefs,  # Analysis on specific properties
            "question_type": discussion_context.get("question_type", "general"),
            "user_budget": current_filters.get("price_max"),
            "user_location": current_filters.get("town"),
            "user_category": current_filters.get("category", "buy")
        }
        
        focused_property = tool_execution_results.get("focused_property", {}) or {}
        comparison_set = tool_execution_results.get("comparison_set", []) or []
        reference_intro = "About the property you referenced"
        if focused_property.get("listing_id"):
            reference_intro = f"About listing #{focused_property.get('listing_id')}"

        deterministic_answer = ""
        if dialogue_act == "compare" and len(comparison_set) >= 2:
            left = comparison_set[0]
            right = comparison_set[1]
            deterministic_answer = (
                f"I compared listing #{left.get('listing_id')} and listing #{right.get('listing_id')}. "
                f"The first is around {left.get('price_egp')} EGP in {left.get('town')}, while the second is around {right.get('price_egp')} EGP in {right.get('town')}. "
                "If you want, I can break it down by value-for-money and livability."
            )
        elif focused_property:
            deterministic_answer = (
                f"{reference_intro}, it is priced around {focused_property.get('price_egp')} EGP, "
                f"offers {focused_property.get('bedrooms')} bedrooms, and is located in {focused_property.get('town')}. "
                "I can also walk you through pros/cons and investment potential."
            )

        discussion_prompt = f"""
        You are an Elite Real Estate Investment Consultant having a consultative conversation with a client.
        The client is asking follow-up questions or seeking your expert opinion on properties.
        
        RECENT PROPERTIES DISCUSSED:
        {json.dumps(comparison_context.get('recent_properties', []), indent=2)}
        
        PROPERTY ANALYSIS DETAILS:
        {json.dumps(comparison_context.get('discussion_details', []), indent=2)}
        
        QUESTION TYPE: {comparison_context.get('question_type')}
        USER BUDGET: {comparison_context.get('user_budget')} EGP
        USER LOCATION PREFERENCE: {comparison_context.get('user_location')}
        USER INTENT: {comparison_context.get('user_category')}
        
        INSTRUCTIONS FOR CONSULTATIVE RESPONSE:
        - OPENING PRIORITY: Start by directly answering the user's exact question in the first 1-2 lines.
        - REFERENCE HANDLING: If user references first/second/that one, acknowledge it explicitly.
        - ACT AS A TRUSTED ADVISOR: Use phrases like "In my professional opinion," "What I'd recommend," "Based on the market data..."
        - FOR COMPARISONS: Highlight trade-offs explicitly (e.g., "Property A is cheaper but Property B has better location").
        - FOR OPINIONS: Back your recommendations with market data and logical reasoning.
        - FOR DETAILS: Provide specific information about price, location, amenities, investment potential, ROI.
        - PROS & CONS: If comparing multiple properties, clearly list the strengths and weaknesses of each.
        - BUDGET DISCUSSION: Help them understand value relative to their budget constraints.
        - TONE: Conversational, friendly, and expert. Use "you" frequently. Make them feel heard and supported.
        - ENGAGEMENT: Ask qualifying questions if needed ("Would a shorter commute be worth 500k more?" or "Are amenities or location more important to you?").
        - NEXT STEPS: Suggest what information might help them decide better.
        """
        
        try:
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Discussion Mode - Calling Model: {target_llm_model} ---")
            llm_response = litellm_completion_with_groq_key_fallback(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": discussion_prompt},
                    {"role": "user", "content": "Please discuss these properties with me and give me your expert perspective."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model

            if "/" not in actual_model_used:
                for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                    if actual_model_used in fallback_candidate:
                        actual_model_used = fallback_candidate
                        break

            discussion_response = llm_response.choices[0].message.content
            if deterministic_answer:
                discussion_response = f"{deterministic_answer}\n\n{discussion_response}"
            if user_language.startswith("ar"):
                discussion_response = translate_to_arabic(discussion_response)
            print(f"--- [TONGUE] Discussion: {target_llm_model} | Actual: {actual_model_used} ---")
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] Discussion LLM failed: {llm_error}")
            discussion_response = "I'd love to discuss these properties with you in more detail! Could you tell me which property you'd like to focus on or what specific aspect interests you most?"
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=discussion_response)],
            "active_model": actual_model_used,
            "response_plan": {
                "answer_first": deterministic_answer or (discussion_response.split("\n")[0] if discussion_response else ""),
                "evidence_block": discussion_briefs[:3],
                "next_step_prompt": "Ask one targeted next-step question tied to commute, budget, or amenities."
            }
        }

    idle_message = "I'm your AI Real Estate Agent. How can I help you navigate the market today?"
    if user_language.startswith("ar"):
        idle_message = translate_to_arabic(idle_message)
    return {
        "messages": [AIMessage(content=idle_message)],
        "response_plan": {
            "answer_first": idle_message,
            "evidence_block": [],
            "next_step_prompt": "Invite user to share budget, area, and property type."
        }
    }
