import os
import sys
import json
import importlib
from typing import Dict, Any
from langchain_core.messages import AIMessage
from dotenv import load_dotenv
import litellm

# Establish path references for cross-module state access
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
AgentState = importlib.import_module("3_state_definition").AgentState

# Load API Keys securely from the parent environment
load_dotenv(os.path.join(os.path.dirname(__file__), "../../.env"))
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    print("!!! [WARNING] GEMINI_API_KEY not found.")
else:
    os.environ["GEMINI_API_KEY"] = gemini_api_key

groq_api_key = os.getenv("GROQ_API_KEY")
if groq_api_key:
    os.environ["GROQ_API_KEY"] = groq_api_key

AGENT_CONFIG = importlib.import_module("1_agent_config").AGENT_CONFIG
PRIMARY_MODEL = AGENT_CONFIG["model"]
FALLBACK_MODELS_LIST = AGENT_CONFIG.get("fallback_models", [])

def translator_node(current_state: AgentState) -> Dict[str, Any]:
    """
    NODE 3: Narrative Generation (The Tongue)
    This node converts raw, backend data frames and execution states into 
    highly polished, conversational English suitable for a premium clientele.
    """
    detected_intent = current_state.get("active_intent")
    missing_required_fields = current_state.get("missing_info", [])
    tool_execution_results = current_state.get("tool_outputs", {})

    print(f"--- [TONGUE] Generating Professional Response ---")

    # 0. Handle API quota exhaustion gracefully by alerting the user explicitly
    if "__quota_exceeded__" in missing_required_fields:
        rate_limit_message = (
            "[!] The AI model is temporarily rate-limited by the API provider. "
            "Please wait a few minutes and try again. Your request has been noted."
        )
        return {"messages": [AIMessage(content=rate_limit_message)]}
    
    # 1. Handle Missing Information dynamically: Differentiate organic misses vs Auditor overrides
    actual_missing_fields = [missing_item for missing_item in missing_required_fields if not str(missing_item).startswith("CORRECTION:")]
    auditor_correction_hint = next((str(missing_item).replace("CORRECTION: ", "") for missing_item in missing_required_fields if str(missing_item).startswith("CORRECTION:")), None)

    if actual_missing_fields:
        # Provide human-friendly definitions for system keys
        human_readable_field_mapping = {
            "town": "location", 
            "property_type": "type of property (apartment/villa)",
            "category": "whether you are looking to buy or rent"
        }
        translated_missing_fields = [human_readable_field_mapping.get(field, field) for field in actual_missing_fields]
        missing_info_response = f"I'd love to help you find the perfect home! Could you please specify the {', '.join(translated_missing_fields)}?"
        return {"messages": [AIMessage(content=missing_info_response)]}
        
    # 2. Process Intent Paths
    if detected_intent in ["search", "analyze"]:
        # Extract underlying context metrics generated by the Recommender/Analyzer
        market_pulse_context = tool_execution_results.get("market_context") or "No general market trends available."
        property_valuation_briefs = tool_execution_results.get("valuation_briefs") or []
        recommendation_results = tool_execution_results.get("recommendations") or {}
        candidate_properties = recommendation_results.get("candidates") or []
        user_maximum_budget = current_state.get("current_filters", {}).get("price_max")
        
        # Expert Logic: Pre-process property data with humanized tags before sending to LLM context
        storytelling_processed_properties = []
        for property_data in candidate_properties[:3]:
            enhanced_property_dict = property_data.copy()
            # Append plain English descriptive fields
            enhanced_property_dict['status'] = "Ready to move in" if str(property_data.get('completion_status')).lower() == 'completed' else "Under construction"
            enhanced_property_dict['size_desc'] = f"Generous {property_data.get('area_value')} sqm layout"
            
            # Formulate budget alignment percentage
            if user_maximum_budget and property_data.get('price_egp'):
                try:
                    property_price = float(property_data['price_egp'])
                    target_budget = float(user_maximum_budget)
                    enhanced_property_dict['budget_fit'] = f"Aligns with { (property_price/target_budget)*100:.1f}% of your target"
                except ValueError: 
                    pass
            storytelling_processed_properties.append(enhanced_property_dict)
        
        # Handle cases where the Recommender found results but deemed the query dangerously vague
        vague_query_instruction = (
            "The user provided very few details. Mention that more specifics would help you find an even more precise match." 
            if recommendation_results.get("is_vague") 
            else "The user provided good details."
        )

        # Inject Auditor Feedback if the previous draft failed validation
        auditor_instruction = auditor_correction_hint if auditor_correction_hint else "None. Just be the best consultant."

        # Build a highly opinionated prompt for narrative storytelling
        narrative_generation_prompt = f"""
        You are an Elite Real Estate Investment Consultant (Concierge Style). 
        Your goal is to present these opportunities with sophistication and expert insight.

        MARKET TRENDS:
        {market_pulse_context}

        SPECIFIC PROPERTY VALUATIONS:
        {json.dumps(property_valuation_briefs, indent=2)}

        RECOMMENDED PROPERTIES (with budget analysis):
        {json.dumps(storytelling_processed_properties, indent=2)}

        INSTRUCTIONS FOR ELITE STORYTELLING:
        - DO NOT just list IDs and prices. Use listing IDs as references (e.g., "Our featured villa, #11225...").
        - LIFESTYLE & FEATURES: Describe the "Generous layout" (Area) and the "Ideal bedroom count."
        - EXPERT ADVICE: If a property is "Ready to move in," highlight the convenience for immediate occupancy. If the payment is "Cash," mention it as a clean, straightforward transaction.
        - TONE: Warm, authoritative, and extremely helpful. Use phrases like "I've personally identified," "Standout match," or "Unique opportunity."
        - BUDGET: Mention the budget scale naturally (e.g. "In that 15 million bracket you mentioned...").
        - CATEGORIZE: 
            - "Primary Match" (The best overall alignment).
            - "Premium Selection" (A high-end option worth stretching for).
            - "Value Choice" (Excellent quality at a more conservative price).
        - CLARITY: If the Analyzer found limited data, frame it as "A niche, exclusive market opportunity."
        - If the Analyzer says a property is 'Competitive' or 'Fair Value', highlight it.
        - UNDER-SPECIFIED REQUEST: {vague_query_instruction}
        
        CRITICAL CORRECTION FROM AUDITOR:
        {auditor_instruction}
        """
        
        try:
            # Execute Generation with Sticky Fallback constraints
            target_llm_model = current_state.get("active_model", PRIMARY_MODEL)
            available_fallbacks = FALLBACK_MODELS_LIST if target_llm_model == PRIMARY_MODEL else []

            print(f"--- [TONGUE] Calling Model: {target_llm_model} ---")
            llm_response = litellm.completion(
                model=target_llm_model,
                messages=[
                    {"role": "system", "content": narrative_generation_prompt},
                    {"role": "user", "content": "Explain these options to me naturally."}
                ],
                fallbacks=available_fallbacks
            )
            actual_model_used = llm_response.model
            
            # Correct provider stripping from LiteLLM
            if "/" not in actual_model_used:
                for fallback_candidate in [PRIMARY_MODEL] + FALLBACK_MODELS_LIST:
                    if actual_model_used in fallback_candidate:
                        actual_model_used = fallback_candidate
                        break
            
            final_narrative_text = llm_response.choices[0].message.content
            print(f"--- [TONGUE] Target: {target_llm_model} | Actual: {actual_model_used} ---")
        except Exception as llm_error:
            print(f"!!! [TONGUE_ERROR] LLM Call failed: {llm_error}")
            final_narrative_text = "I've analyzed the market and found some options for you. However, I'm having trouble generating the detailed report right now. Would you like to see the raw list?"
            actual_model_used = target_llm_model

        return {
            "messages": [AIMessage(content=final_narrative_text)],
            "active_model": actual_model_used
        }
        
    elif detected_intent == "book" and "booking_response" in tool_execution_results:
        # Handle the successful orchestration of a database Booking
        booking_registration_result = tool_execution_results["booking_response"]
        
        if booking_registration_result["status"] == "SUCCESS":
            booking_success_message = f"Fantastic! I've successfully registered your appointment. Your Booking ID is **{booking_registration_result['booking_id']}**. One of our expert consultants will contact you shortly to confirm the details."
        else:
            booking_success_message = "I'm sorry, I couldn't complete the registration. It seems some information is still missing. Could you please provide your name and phone number?"
            
        return {"messages": [AIMessage(content=booking_success_message)]}
        
    # 3. Default state response (Greeting or casual query)
    idle_message = "I'm your AI Real Estate Agent. How can I help you navigate the market today?"
    return {"messages": [AIMessage(content=idle_message)]}
