import json

class LLMContextBuilder:
    """
    LAYER 3: LLM CONTEXT PREPARATION
    This module takes the structured dictionaries generated by the MarketEngine and PreferenceEngine
    and formats them into standardized, rigorously clean Context Payloads. 
    The LangGraph Chatbot module will inject these exact text payloads into its system prompt, 
    allowing the LLM to narrate complex statistics naturally without hallucinating fake numbers.
    """
    
    @staticmethod
    def prepare_fair_price_context(analytical_result: dict) -> str:
        """Transforms the mathematical Fair Price dictionary into a readable LLM context block."""
        if analytical_result['status'] != 'success':
            return ""  # Silently skip — never expose data errors to the LLM prompt
            
        market_stats = analytical_result['market_stats']
        user_query = analytical_result['query']
        confidence_score = market_stats.get('confidence_score', 0)
        
        context_payload = (
            f"[FAIR_PRICE_CONTEXT]\n"
            f"- Query: {user_query['bedrooms']} bed {user_query['property_type']} in {user_query['town']}\n"
            f"- Asking Price: {user_query['asking_price']:,.0f} EGP\n"
            f"- Market Median: {market_stats.get('median_price', market_stats.get('predicted_fair_price', 0)):,.0f} EGP\n"
            f"- Comparable Data Points: {market_stats['comparable_listings_count']}\n"
            f"- Price Percentile: {market_stats['price_percentile']}th percentile\n"
            f"- Analyst Verdict: {analytical_result['verdict'].upper().replace('_', ' ')}\n"
            f"- Statistical Confidence: {int(confidence_score*100)}%\n"
        )
        return context_payload

    @staticmethod
    def prepare_investment_context(analytical_result: dict) -> str:
        """Formats the list of identified investment gems for LLM injection."""
        if analytical_result['status'] != 'success':
            return ""  # Silently skip
            
        context_payload = "[INVESTMENT_SCOUTER_CONTEXT]\n"
        context_payload += f"- Market Median for Area: {analytical_result['market_median']:,.0f} EGP\n"
        
        for index, gem_property in enumerate(analytical_result['gems'], 1):
            context_payload += f"- Opportunity {index}: Listing ID {gem_property['listing_id']} ({gem_property['bedrooms']} bed) is {int(gem_property['undervalue_pct']*100)}% BELOW the market median.\n"
            
        return context_payload

    @staticmethod
    def prepare_market_pulse_context(pulse_snapshot: dict) -> str:
        """Transforms the Macroscopic Global Market Pulse data into an LLM context block."""
        context_payload = "[MARKET_PULSE_CONTEXT]\n"
        
        volume_data = pulse_snapshot.get('market_volume', {})
        context_payload += f"- Total Active Listings: {volume_data.get('total_active_listings', 0)}\n"
        context_payload += f"- Buy vs Rent Split: {volume_data.get('buy_count', 0)} Buy / {volume_data.get('rent_count', 0)} Rent\n"
        
        economic_data = pulse_snapshot.get('price_economics', {})
        context_payload += f"- Median Buy Price: {economic_data.get('median_buy_price', 0):,.0f} EGP\n"
        context_payload += f"- Median Rent Price: {economic_data.get('median_rent_price', 0):,.0f} EGP\n"
        
        health_data = pulse_snapshot.get('market_health', {})
        context_payload += f"- Premium/Verified Listings: {health_data.get('premium_verified_listings_pct', 0)}%\n"
        
        financing_mix = health_data.get('buyer_financing_mix', {})
        financing_string = ", ".join([f"{method}: {percentage}%" for method, percentage in financing_mix.items()])
        context_payload += f"- Buyer Financing Mix: {financing_string}\n"
        
        return context_payload

    @staticmethod
    def prepare_segment_report_context(report_data: dict) -> str:
        """Transforms the Personal Segment Report data into an LLM context block."""
        if report_data['status'] != 'success':
            return ""  # Silently skip
            
        report_dictionary = report_data['report']
        segment_stats = report_dictionary['stats']
        
        context_payload = (
            f"[PERSONAL_MARKET_SEGMENT_CONTEXT]\n"
            f"- Segment Size: {report_dictionary['segment_size']} highly recommended listings\n"
            f"- Segment Median Price: {segment_stats['median_price']:,.0f} EGP\n"
            f"- Price Range: {segment_stats['price_range'][0]:,.0f} EGP to {segment_stats['price_range'][1]:,.0f} EGP\n"
            f"- Average Area: {segment_stats['avg_area']:.0f} sqm\n"
        )
        
        completion_mix = segment_stats['completion_mix']
        completion_string = ", ".join([f"{status}: {percentage}%" for status, percentage in completion_mix.items()])
        context_payload += f"- Completion Mix: {completion_string}\n"
        
        payment_mix = segment_stats['payment_mix']
        payment_string = ", ".join([f"{method}: {percentage}%" for method, percentage in payment_mix.items()])
        context_payload += f"- Payment Mix: {payment_string}\n"
        
        return context_payload

    @staticmethod
    def prepare_tradeoff_context(tradeoff_data: dict) -> str:
        """Transforms the Trade-off Advisor data into an LLM context block."""
        if tradeoff_data['status'] != 'success':
            return ""  # Silently skip
            
        context_payload = f"[TRADEOFF_ADVISOR_CONTEXT]\n"
        context_payload += f"- Current Exact Matches: {tradeoff_data['current_matches']}\n"
        
        suggested_adjustments = tradeoff_data.get('adjustments', [])
        if not suggested_adjustments:
            context_payload += "- Suggested Adjustments: None. Current filters are broad enough.\n"
        else:
            for index, adjustment in enumerate(suggested_adjustments, 1):
                context_payload += f"- Suggestion {index}: {adjustment['change']} -> unlocks {adjustment['delta']} ({adjustment['new_matches']} total matches)\n"
                
        return context_payload

if __name__ == "__main__":
    # Test block to verify output formatting when run as a standalone script
    mock_fair_price_data = {
        "status": "success",
        "verdict": "highly_competitive",
        "query": {"bedrooms": 3, "property_type": "Apartment", "town": "New Cairo City", "asking_price": 5200000},
        "market_stats": {"comparable_listings_count": 826, "median_price": 7900000, "price_percentile": 23.9}
    }
    print(LLMContextBuilder.prepare_fair_price_context(mock_fair_price_data))
